### PR TITLE
Weaken numpy requirement

### PR DESCRIPTION
**Pull request by diehlbw**
Addresses #183 by weakening the pinning on numpy.

While I agree in spirit with the [comment on not having strict pinnings](https://github.com/dssg/aequitas/issues/183#issuecomment-2161505071) I tried not to increase scope of changes more than necessary to hopefully reduce back-and-forth

### CODE REVIEW

**Comment by diehlbw** [comment]
@sgpjesus - what is the process to get feedback on this?  is it something that can be considered?

**Comment by sgpjesus** [comment]
Hi @diehlbw, sorry for the delay. The process is still not very defined yet, for now I wanted to finish the merge request on using poetry before advancing with any dependency changes!

**Comment by sgpjesus** [comment]
Hi @diehlbw, Thank you for your PR. We are working on extending the unit tests; it would be easier to see if weakening the numpy requirement would affect anything after that. Still, I ask you to pull the changes in Master, and update the `pyproject.toml` file.

**Comment by diehlbw** [comment]
Closing since this is effectively fixed with the latest commit.  

Also want to convey some considerations that non-trivial updates to requirements files should often be considered **breaking** changes (ie correspond to major version bump, or at least a minor one depending on your update patterns). 
Environments that had been constructed to work with the old v1.0.0, may not work if other packages are pinned/constrained; much less code itself.

**Pull request closed without merging**
